-- Aufgabe 12.1
CREATE VIEW EMPLOYEES_VU AS
SELECT EMPLOYEE_ID,
       LAST_NAME,
       DEPARTMENT_ID
FROM EMPLOYEES;

-- Aufgabe 12.2
SELECT * FROM EMPLOYEES_VU;

-- Aufgabe 12.3
SELECT 
    lAST_NAME,
    DEPARTMENT_ID
FROM EMPLOYEES_VU;

-- Aufgabe 12.4
CREATE VIEW DEPT50 AS
SELECT EMPLOYEE_ID AS EMPNO,
       LAST_NAME AS EMPLOYEE,
       DEPARTMENT_ID AS DEPTNO
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
WITH CHECK OPTION;

-- Aufgabe 12.5
SELECT * FROM DEPT50;

-- Aufgabe 12.6
UPDATE DEPT50
SET DEPTNO = 80
WHERE EMPLOYEE = 'Matos';

-- Aufgabe 12.7
CREATE SEQUENCE DEPT_ID_SEQ
  START WITH 200
  INCREMENT BY 10
  MAXVALUE 1000
  NOCACHE
  NOCYCLE;
  
-- Aufgabe 12.8
INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (DEPT_ID_SEQ.NEXTVAL, 'EDUCATION', 'BERLIN');

INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (DEPT_ID_SEQ.NEXTVAL, 'ADMINISTRATION', 'MÜNCHEN');

COMMIT;



